In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

def importdata():
	balance_data = pd.read_csv("cropRecommend.csv")
	
	#print ("Dataset Length: ", len(balance_data))
	#print ("Dataset Shape: ", balance_data.shape)
	
	#print ("Dataset: ",balance_data.head())
	return balance_data


def splitdataset(balance_data):
 	# Separating the target variable
	X = balance_data.values[:, 0:11]
	Y = balance_data.values[:, 11]
	
	X_train, X_test, y_train, y_test = train_test_split(
	X, Y, test_size = 0.3, random_state = 100)
	
	return X, Y, X_train, X_test, y_train, y_test
	
    
    
	
# Function to perform training with entropy.
def tarin_using_entropy(X_train, X_test, y_train):
	
	clf_entropy = DecisionTreeClassifier(
			criterion = "entropy", random_state = 100,
			max_depth = 15, min_samples_leaf = 5)
	
	clf_entropy.fit(X_train, y_train)
	return clf_entropy

def prediction(X_test, clf_object):
	
	y_pred = clf_object.predict(X_test)
	print("Predicted values:")
	
	return y_pred
	

    
def cal_accuracy(y_test, y_pred):
	
	print("Confusion Matrix: \n",
		confusion_matrix(y_test, y_pred))
	
	print ("Accuracy : ",
	accuracy_score(y_test,y_pred)*100)
	
	print("Report : ",
	classification_report(y_test, y_pred, zero_division=1))
    
    
def main():
    # Building Phase
    data = importdata()
    X, Y, X_train, X_test, y_train, y_test = splitdataset(data)
    
    
    clf_entropy = tarin_using_entropy(X_train, X_test, y_train)
    
    clf_gini = train_using_gini(X_train, X_test, y_train)
    
    
    print("Results Using Entropy:")
    # Prediction using entropy
    y_pred_entropy = prediction(X_test, clf_entropy)
    cal_accuracy(y_test, y_pred_entropy)
    
    print("Results Using Gini")
    # Prediction using gini
    y_pred_gini = prediction(X_test, clf_gini)
    cal_accuracy(y_test, y_pred_gini)
    

def train_using_gini(X_train, X_test, y_train):
    clf_gini = DecisionTreeClassifier(criterion = "gini",
            random_state = 100,max_depth=14, min_samples_leaf=5)
  
    clf_gini.fit(X_train, y_train)
    return clf_gini
    

if __name__=="__main__":
	main()
    

Results Using Entropy:
Predicted values:
Confusion Matrix: 
 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0 26  0  0  0  0  3  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 35  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 27  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 31  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 28  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0 37  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0 27  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 33  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 28  0  0  0  